// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package role_policies

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if len(a.ko.Spec.PolicyARNs) != len(b.ko.Spec.PolicyARNs) {
		delta.Add("Spec.PolicyARNs", a.ko.Spec.PolicyARNs, b.ko.Spec.PolicyARNs)
	} else if len(a.ko.Spec.PolicyARNs) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.PolicyARNs, b.ko.Spec.PolicyARNs) {
			delta.Add("Spec.PolicyARNs", a.ko.Spec.PolicyARNs, b.ko.Spec.PolicyARNs)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.PolicyARN, b.ko.Spec.PolicyARN) {
		delta.Add("Spec.PolicyARN", a.ko.Spec.PolicyARN, b.ko.Spec.PolicyARN)
	} else if a.ko.Spec.PolicyARN != nil && b.ko.Spec.PolicyARN != nil {
		if *a.ko.Spec.PolicyARN != *b.ko.Spec.PolicyARN {
			delta.Add("Spec.PolicyARN", a.ko.Spec.PolicyARN, b.ko.Spec.PolicyARN)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RoleName, b.ko.Spec.RoleName) {
		delta.Add("Spec.RoleName", a.ko.Spec.RoleName, b.ko.Spec.RoleName)
	} else if a.ko.Spec.RoleName != nil && b.ko.Spec.RoleName != nil {
		if *a.ko.Spec.RoleName != *b.ko.Spec.RoleName {
			delta.Add("Spec.RoleName", a.ko.Spec.RoleName, b.ko.Spec.RoleName)
		}
	}

	return delta
}
