// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package open_id_connect_provider

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}
	customPreCompare(delta, a, b)

	if len(a.ko.Spec.ClientIDs) != len(b.ko.Spec.ClientIDs) {
		delta.Add("Spec.ClientIDs", a.ko.Spec.ClientIDs, b.ko.Spec.ClientIDs)
	} else if len(a.ko.Spec.ClientIDs) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.ClientIDs, b.ko.Spec.ClientIDs) {
			delta.Add("Spec.ClientIDs", a.ko.Spec.ClientIDs, b.ko.Spec.ClientIDs)
		}
	}
	if len(a.ko.Spec.Thumbprints) != len(b.ko.Spec.Thumbprints) {
		delta.Add("Spec.Thumbprints", a.ko.Spec.Thumbprints, b.ko.Spec.Thumbprints)
	} else if len(a.ko.Spec.Thumbprints) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.Thumbprints, b.ko.Spec.Thumbprints) {
			delta.Add("Spec.Thumbprints", a.ko.Spec.Thumbprints, b.ko.Spec.Thumbprints)
		}
	}

	return delta
}
