---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-iam-reader
  namespace: default
rules:
- apiGroups:
  - iam.services.k8s.aws
  resources:
  - groups
  - openidconnectproviders
  - policies
  - roles
  verbs:
  - get
  - list
  - watch
