// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package policies

import (
	"context"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackmetrics "github.com/aws-controllers-k8s/runtime/pkg/metrics"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/iam"

	svcapitypes "github.com/aws-controllers-k8s/iam-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &ackv1alpha1.AWSIdentifiers{}
)

type BasePoliciesManager interface {
	toPoliciess([]resource) []Policies
	toResource([]Policies) []*resource
}

type PoliciesManager struct {
	BasePoliciesManager
	rm resourceManager
}

// toPoliciess converts a slice of resources into a slice of Policies items.
func (m *PoliciesManager) toPoliciess(resources []resource) []Policies {
	result := make([]Policies, 0, len(resources))
	for _, r := range resources {
		result = append(result, Policies{
			r: r,
		})
	}
	return result
}

// toResource converts a slice of Policies items back into resource pointers.
func (m *PoliciesManager) toResource(items []Policies) []*resource {
	result := make([]*resource, 0, len(items))
	for _, item := range items {
		r := item.r
		result = append(result, &r)
	}
	return result
}

// Sync reconciles the sub-resource collection by comparing the desired and
// latest state, computing a diff, and issuing the necessary create/update/
// delete SDK calls to bring AWS in line with the desired spec.
func (m *PoliciesManager) Sync(
	ctx context.Context,
	desired []resource,
	latest []resource,
) error {
	var err error
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("r.Sync")
	defer func() {
		exit(err)
	}()

	var toCreate, toUpdate, toDelete []*resource
	var delta Delta[Policies]

	desiredPoliciess := m.toPoliciess(desired)
	latestPoliciess := m.toPoliciess(latest)

	delta = ComputeDelta(desiredPoliciess, latestPoliciess)

	// Create any sub-resource items that exist in desired but not in latest.
	if len(delta.toCreate) > 0 {
		toCreate = m.toResource(delta.toCreate)
		for _, create := range toCreate {
			_, err := m.rm.Create(ctx, create)
			if err != nil {
				return err
			}
		}
	}

	// Update any sub-resource items that exist in both but have changed.
	if len(delta.toUpdate) > 0 {
		toUpdate = m.toResource(delta.toUpdate)
		for _, update := range toUpdate {
			_, err := m.rm.Create(ctx, update)
			if err != nil {
				return err
			}
		}
	}

	// Delete any sub-resource items that exist in latest but not in desired.
	if len(delta.toDelete) > 0 {
		toDelete = m.toResource(delta.toDelete)
		for _, delete := range toDelete {
			_, err := m.rm.Delete(ctx, delete)
			if err != nil {
				return err
			}
		}
	}

	return nil
}

// Manager wraps the generated PoliciesManager and provides conversion
// logic for transforming parent resource specs into sub-resource collections.
type Manager struct {
	pm *PoliciesManager
}

// NewManager creates a Manager using the provided SDK client and metrics
// recorder.
func NewManager(
	sdkapi *svcsdk.Client,
	metrics *ackmetrics.Metrics,
) *Manager {
	return &Manager{
		pm: &PoliciesManager{
			rm: resourceManager{
				sdkapi:  sdkapi,
				metrics: metrics,
			},
		},
	}
}

// Sync converts the desired and latest parent specs into internal resource
// slices using the configured conversion logic, then delegates to
// PoliciesManager.Sync.
func (m *Manager) Sync(
	ctx context.Context,
	desiredSpec any,
	latestSpec any,
) error {
	desired := ConvertToResources(desiredSpec)
	latest := ConvertToResources(latestSpec)
	return m.pm.Sync(ctx, desired, latest)
}

// ConvertToResources converts a parent resource into a slice of internal resource
// objects by type-switching on the top-level resource type to find the matching
// source configuration, then iterating over the parent collection and applying
// element and field mappings.
func ConvertToResources(
	spec any,
) []resource {
	if spec == nil {
		return nil
	}

	switch v := spec.(type) {
	case svcapitypes.Role:
		return convertFromRole(v)
	case *svcapitypes.Role:
		if v == nil {
			return nil
		}
		return convertFromRole(*v)
	}
	return nil
}

// convertFromRole handles conversion when the parent resource is Role.
func convertFromRole(parent svcapitypes.Role) []resource {
	collection := parent.Spec.Policies
	if collection == nil {
		return nil
	}

	var resources []resource

	for _, elem := range collection {
		ko := &svcapitypes.Policies{}
		// Element mapping: PolicyARN ← element itself (scalar "." token)
		ko.Spec.PolicyARN = elem
		// Field mapping: RoleName ← parent.Spec.Name
		ko.Spec.RoleName = parent.Spec.Name
		resources = append(resources, resource{ko: ko})
	}

	return resources
}

// Delta holds the result of comparing desired vs. latest sub-resource items.
// It partitions items into three buckets — create, update, and delete — so the
// SubResourceManager can issue the minimal set of AWS API calls to reconcile
// the sub-resource collection.
type Delta[T BaseSubResource] struct {
	// toCreate contains items present in desired but absent from latest.
	toCreate []T
	// toUpdate contains items present in both but whose underlying resource
	// differs (detected by newResourceDelta).
	toUpdate []T
	// toDelete contains items present in latest but absent from desired.
	toDelete []T
}

// ComputeDelta performs a key-based diff between the desired and latest
// sub-resource slices. It uses Key() for identity (does this item exist?) and
// newResourceDelta for change detection (has this item changed?). The resulting
// Delta tells the SubResourceManager exactly which items need to be created,
// updated, or deleted.
func ComputeDelta[T BaseSubResource](desired, latest []T) Delta[T] {
	delta := Delta[T]{}
	latestMap := make(map[string]T)
	for _, l := range latest {
		latestMap[l.Key()] = l
	}

	desiredMap := make(map[string]bool)
	for _, d := range desired {
		key := d.Key()
		desiredMap[key] = true
		if lat, exists := latestMap[key]; !exists {
			delta.toCreate = append(delta.toCreate, d)
		} else {
			dr := d.resource()
			lr := lat.resource()
			rdelta := newResourceDelta(&dr, &lr)
			if len(rdelta.Differences) > 0 {
				delta.toUpdate = append(delta.toUpdate, d)
			}
		}
	}

	for key, lat := range latestMap {
		if !desiredMap[key] {
			delta.toDelete = append(delta.toDelete, lat)
		}
	}
	return delta
}

// BaseSubResource defines the interface that each individual sub-resource item
// must implement. Each item represents a single entry in a sub-resource
// collection.
type BaseSubResource interface {
	// Key returns the unique identifier for this item within the collection.
	Key() string
	// resource returns the underlying resource for delta comparison.
	resource() resource
}

type Policies struct {
	r resource
}

// Key returns the primary key value as a string identifier for this sub-resource.
func (t Policies) Key() string {
	return *t.r.ko.Spec.PolicyARN
}

// resource returns the underlying resource for delta comparison.
func (t Policies) resource() resource {
	return t.r
}
