// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package policies

import (
	"context"
	"fmt"

	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/mitchellh/hashstructure/v2"
)

type BasePoliciesManager interface {
	toPoliciess([]resource) []Policies
	toResource([]Policies) []*resource
}

type PoliciesManager struct {
	BasePoliciesManager
	rm resourceManager
}

// toPoliciess converts a slice of resources into a slice of Policies items.
func (m *PoliciesManager) toPoliciess(resources []resource) []Policies {
	result := make([]Policies, 0, len(resources))
	for _, r := range resources {
		result = append(result, Policies{
			r: r,
		})
	}
	return result
}

// toResource converts a slice of Policies items back into resource pointers.
func (m *PoliciesManager) toResource(items []Policies) []*resource {
	result := make([]*resource, 0, len(items))
	for _, item := range items {
		r := item.r
		result = append(result, &r)
	}
	return result
}

// Sync reconciles the sub-resource collection by comparing the desired and
// latest state, computing a diff, and issuing the necessary create/update/
// delete SDK calls to bring AWS in line with the desired spec.
func (m *PoliciesManager) Sync(
	ctx context.Context,
	desired []resource,
	latest []resource,
) error {
	var err error
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("r.Sync")
	defer func() {
		exit(err)
	}()

	var toCreate, toUpdate, toDelete []*resource
	var delta Delta[Policies]

	desiredPoliciess := m.toPoliciess(desired)
	latestPoliciess := m.toPoliciess(latest)

	delta = ComputeDelta(desiredPoliciess, latestPoliciess)

	// Create any sub-resource items that exist in desired but not in latest.
	if len(delta.toCreate) > 0 {
		toCreate = m.toResource(delta.toCreate)
		for _, create := range toCreate {
			_, err := m.rm.Create(ctx, create)
			if err != nil {
				return err
			}
		}

	}

	// Update any sub-resource items that exist in both but have changed.
	if len(delta.toUpdate) > 0 {
		toUpdate = m.toResource(delta.toUpdate)
		for _, update := range toUpdate {
			_, err := m.rm.Create(ctx, update)
			if err != nil {
				return err
			}
		}

	}

	// Delete any sub-resource items that exist in latest but not in desired.
	if len(delta.toDelete) > 0 {
		toDelete = m.toResource(delta.toDelete)
		for _, delete := range toDelete {
			_, err := m.rm.Delete(ctx, delete)
			if err != nil {
				return err
			}
		}

	}

	return nil
}

// Delta holds the result of comparing desired vs. latest sub-resource items.
// It partitions items into three buckets — create, update, and delete — so the
// SubResourceManager can issue the minimal set of AWS API calls to reconcile
// the sub-resource collection.
type Delta[T BaseSubResource] struct {
	// toCreate contains items present in desired but absent from latest.
	toCreate []T
	// toUpdate contains items present in both but whose Hash() differs,
	// indicating the item's state has changed.
	toUpdate []T
	// toDelete contains items present in latest but absent from desired.
	toDelete []T
}

// ComputeDelta performs a key-based diff between the desired and latest
// sub-resource slices. It uses Key() for identity (does this item exist?) and
// Hash() for equality (has this item changed?). The resulting Delta tells the
// SubResourceManager exactly which items need to be created, updated, or
// deleted.
func ComputeDelta[T BaseSubResource](desired, latest []T) Delta[T] {
	delta := Delta[T]{}
	latestMap := make(map[string]T)
	for _, l := range latest {
		latestMap[Hash(l.Key())] = l
	}

	desiredMap := make(map[string]bool)
	for _, d := range desired {
		desiredMap[Hash(d.Key())] = true
		if lat, exists := latestMap[Hash(d.Key())]; !exists {
			delta.toCreate = append(delta.toCreate, d)
		} else if Hash(d.Value()) != Hash(lat.Value()) {
			delta.toUpdate = append(delta.toUpdate, d)
		}
	}

	for id, lat := range latestMap {
		if !desiredMap[id] {
			delta.toDelete = append(delta.toDelete, lat)
		}
	}
	return delta
}

// BaseSubResource defines the interface that each individual sub-resource item
// must implement. Each item represents a single entry in a sub-resource
// collection.
type BaseSubResource interface {
	// Key returns the unique identifier for this item within the collection.
	Key() any
	// Value returns the meaningful content of this item.
	Value() any
}

// SubResource provides a default Hash implementation for any BaseSubResource
// using structural hashing. Concrete sub-resource types can embed this to get
// automatic hash computation based on their Value().
type SubResource struct {
	BaseSubResource
}

type Policies struct {
	*SubResource
	r resource
}

// Key returns the policies key as the unique identifier.
func (t Policies) Key() any {
	return t.r.ko.Spec.PolicyARN
}

// Value returns the policies value.
func (t Policies) Value() any {
	return t.r.ko.Spec.PolicyARN
}

func Hash(value any) string {
	hash, err := hashstructure.Hash(value, hashstructure.FormatV2, nil)
	if err != nil {
		return ""
	}
	return fmt.Sprintf("%d", hash)
}
