---
annotations:
  capabilityLevel: Basic Install
  shortDescription: AWS IAM controller is a service controller for managing IAM resources
    in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon IAM
description: |-
  Manage Identity and Access Management (IAM) resources in AWS from within your Kubernetes cluster.


  **About Amazon IAM**


  AWS Identity and Access Management (IAM) is a web service that helps you securely control access to AWS resources. You use IAM to control who is authenticated (signed in) and authorized (has permissions) to use resources.


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project.


  **Pre-Installation Steps**


  Please follow the following link: [Red Hat OpenShift](https://aws-controllers-k8s.github.io/community/docs/user-docs/openshift/)
samples:
- kind: Policy
  spec: '{}'
- kind: Role
  spec: '{}'
- kind: Group
  spec: '{}'
- kind: OpenIDConnectProvider
  spec: '{}'
- kind: User
  spec: '{}'
maintainers:
- name: "iam maintainer team"
  email: "ack-maintainers@amazon.com"
links:
- name: Amazon IAM Developer Resources
  url: https://aws.amazon.com/iam/resources/
