// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package login_profile

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Password, b.ko.Spec.Password) {
		delta.Add("Spec.Password", a.ko.Spec.Password, b.ko.Spec.Password)
	} else if a.ko.Spec.Password != nil && b.ko.Spec.Password != nil {
		if *a.ko.Spec.Password != *b.ko.Spec.Password {
			delta.Add("Spec.Password", a.ko.Spec.Password, b.ko.Spec.Password)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.PasswordResetRequired, b.ko.Spec.PasswordResetRequired) {
		delta.Add("Spec.PasswordResetRequired", a.ko.Spec.PasswordResetRequired, b.ko.Spec.PasswordResetRequired)
	} else if a.ko.Spec.PasswordResetRequired != nil && b.ko.Spec.PasswordResetRequired != nil {
		if *a.ko.Spec.PasswordResetRequired != *b.ko.Spec.PasswordResetRequired {
			delta.Add("Spec.PasswordResetRequired", a.ko.Spec.PasswordResetRequired, b.ko.Spec.PasswordResetRequired)
		}
	}

	return delta
}
