// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package service_linked_role

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.AWSServiceName, b.ko.Spec.AWSServiceName) {
		delta.Add("Spec.AWSServiceName", a.ko.Spec.AWSServiceName, b.ko.Spec.AWSServiceName)
	} else if a.ko.Spec.AWSServiceName != nil && b.ko.Spec.AWSServiceName != nil {
		if *a.ko.Spec.AWSServiceName != *b.ko.Spec.AWSServiceName {
			delta.Add("Spec.AWSServiceName", a.ko.Spec.AWSServiceName, b.ko.Spec.AWSServiceName)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.CustomSuffix, b.ko.Spec.CustomSuffix) {
		delta.Add("Spec.CustomSuffix", a.ko.Spec.CustomSuffix, b.ko.Spec.CustomSuffix)
	} else if a.ko.Spec.CustomSuffix != nil && b.ko.Spec.CustomSuffix != nil {
		if *a.ko.Spec.CustomSuffix != *b.ko.Spec.CustomSuffix {
			delta.Add("Spec.CustomSuffix", a.ko.Spec.CustomSuffix, b.ko.Spec.CustomSuffix)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	} else if a.ko.Spec.Description != nil && b.ko.Spec.Description != nil {
		if *a.ko.Spec.Description != *b.ko.Spec.Description {
			delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
		}
	}

	return delta
}
