// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package role_tags

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.Key, b.ko.Spec.Key) {
		delta.Add("Spec.Key", a.ko.Spec.Key, b.ko.Spec.Key)
	} else if a.ko.Spec.Key != nil && b.ko.Spec.Key != nil {
		if *a.ko.Spec.Key != *b.ko.Spec.Key {
			delta.Add("Spec.Key", a.ko.Spec.Key, b.ko.Spec.Key)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RoleName, b.ko.Spec.RoleName) {
		delta.Add("Spec.RoleName", a.ko.Spec.RoleName, b.ko.Spec.RoleName)
	} else if a.ko.Spec.RoleName != nil && b.ko.Spec.RoleName != nil {
		if *a.ko.Spec.RoleName != *b.ko.Spec.RoleName {
			delta.Add("Spec.RoleName", a.ko.Spec.RoleName, b.ko.Spec.RoleName)
		}
	}
	if len(a.ko.Spec.TagKeys) != len(b.ko.Spec.TagKeys) {
		delta.Add("Spec.TagKeys", a.ko.Spec.TagKeys, b.ko.Spec.TagKeys)
	} else if len(a.ko.Spec.TagKeys) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.TagKeys, b.ko.Spec.TagKeys) {
			delta.Add("Spec.TagKeys", a.ko.Spec.TagKeys, b.ko.Spec.TagKeys)
		}
	}
	if len(a.ko.Spec.Tags) != len(b.ko.Spec.Tags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	} else if len(a.ko.Spec.Tags) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Tags, b.ko.Spec.Tags) {
			delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
		}
	}

	return delta
}
