// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type AccessAdvisorUsageGranularityType string

const (
	AccessAdvisorUsageGranularityType_ACTION_LEVEL  AccessAdvisorUsageGranularityType = "ACTION_LEVEL"
	AccessAdvisorUsageGranularityType_SERVICE_LEVEL AccessAdvisorUsageGranularityType = "SERVICE_LEVEL"
)

type AssignmentStatusType string

const (
	AssignmentStatusType_Any        AssignmentStatusType = "Any"
	AssignmentStatusType_Assigned   AssignmentStatusType = "Assigned"
	AssignmentStatusType_Unassigned AssignmentStatusType = "Unassigned"
)

type ContextKeyTypeEnum string

const (
	ContextKeyTypeEnum_binary      ContextKeyTypeEnum = "binary"
	ContextKeyTypeEnum_binaryList  ContextKeyTypeEnum = "binaryList"
	ContextKeyTypeEnum_boolean     ContextKeyTypeEnum = "boolean"
	ContextKeyTypeEnum_booleanList ContextKeyTypeEnum = "booleanList"
	ContextKeyTypeEnum_date        ContextKeyTypeEnum = "date"
	ContextKeyTypeEnum_dateList    ContextKeyTypeEnum = "dateList"
	ContextKeyTypeEnum_ip          ContextKeyTypeEnum = "ip"
	ContextKeyTypeEnum_ipList      ContextKeyTypeEnum = "ipList"
	ContextKeyTypeEnum_numeric     ContextKeyTypeEnum = "numeric"
	ContextKeyTypeEnum_numericList ContextKeyTypeEnum = "numericList"
	ContextKeyTypeEnum_string      ContextKeyTypeEnum = "string"
	ContextKeyTypeEnum_stringList  ContextKeyTypeEnum = "stringList"
)

type DeletionTaskStatusType string

const (
	DeletionTaskStatusType_FAILED      DeletionTaskStatusType = "FAILED"
	DeletionTaskStatusType_IN_PROGRESS DeletionTaskStatusType = "IN_PROGRESS"
	DeletionTaskStatusType_NOT_STARTED DeletionTaskStatusType = "NOT_STARTED"
	DeletionTaskStatusType_SUCCEEDED   DeletionTaskStatusType = "SUCCEEDED"
)

type EncodingType string

const (
	EncodingType_PEM EncodingType = "PEM"
	EncodingType_SSH EncodingType = "SSH"
)

type EntityType string

const (
	EntityType_AWSManagedPolicy   EntityType = "AWSManagedPolicy"
	EntityType_Group              EntityType = "Group"
	EntityType_LocalManagedPolicy EntityType = "LocalManagedPolicy"
	EntityType_Role               EntityType = "Role"
	EntityType_User               EntityType = "User"
)

type FeatureType string

const (
	FeatureType_RootCredentialsManagement FeatureType = "RootCredentialsManagement"
	FeatureType_RootSessions              FeatureType = "RootSessions"
)

type GlobalEndpointTokenVersion string

const (
	GlobalEndpointTokenVersion_v1Token GlobalEndpointTokenVersion = "v1Token"
	GlobalEndpointTokenVersion_v2Token GlobalEndpointTokenVersion = "v2Token"
)

type JobStatusType string

const (
	JobStatusType_COMPLETED   JobStatusType = "COMPLETED"
	JobStatusType_FAILED      JobStatusType = "FAILED"
	JobStatusType_IN_PROGRESS JobStatusType = "IN_PROGRESS"
)

type PermissionsBoundaryAttachmentType string

const (
	PermissionsBoundaryAttachmentType_PermissionsBoundaryPolicy PermissionsBoundaryAttachmentType = "PermissionsBoundaryPolicy"
)

type PolicyEvaluationDecisionType string

const (
	PolicyEvaluationDecisionType_allowed      PolicyEvaluationDecisionType = "allowed"
	PolicyEvaluationDecisionType_explicitDeny PolicyEvaluationDecisionType = "explicitDeny"
	PolicyEvaluationDecisionType_implicitDeny PolicyEvaluationDecisionType = "implicitDeny"
)

type PolicyOwnerEntityType string

const (
	PolicyOwnerEntityType_GROUP PolicyOwnerEntityType = "GROUP"
	PolicyOwnerEntityType_ROLE  PolicyOwnerEntityType = "ROLE"
	PolicyOwnerEntityType_USER  PolicyOwnerEntityType = "USER"
)

type PolicyScopeType string

const (
	PolicyScopeType_AWS   PolicyScopeType = "AWS"
	PolicyScopeType_All   PolicyScopeType = "All"
	PolicyScopeType_Local PolicyScopeType = "Local"
)

type PolicySourceType string

const (
	PolicySourceType_aws_managed  PolicySourceType = "aws-managed"
	PolicySourceType_group        PolicySourceType = "group"
	PolicySourceType_none         PolicySourceType = "none"
	PolicySourceType_resource     PolicySourceType = "resource"
	PolicySourceType_role         PolicySourceType = "role"
	PolicySourceType_user         PolicySourceType = "user"
	PolicySourceType_user_managed PolicySourceType = "user-managed"
)

type PolicyType string

const (
	PolicyType_INLINE  PolicyType = "INLINE"
	PolicyType_MANAGED PolicyType = "MANAGED"
)

type PolicyUsageType string

const (
	PolicyUsageType_PermissionsBoundary PolicyUsageType = "PermissionsBoundary"
	PolicyUsageType_PermissionsPolicy   PolicyUsageType = "PermissionsPolicy"
)

type ReportFormatType string

const (
	ReportFormatType_text_csv ReportFormatType = "text/csv"
)

type ReportStateType string

const (
	ReportStateType_COMPLETE   ReportStateType = "COMPLETE"
	ReportStateType_INPROGRESS ReportStateType = "INPROGRESS"
	ReportStateType_STARTED    ReportStateType = "STARTED"
)

type SortKeyType string

const (
	SortKeyType_LAST_AUTHENTICATED_TIME_ASCENDING  SortKeyType = "LAST_AUTHENTICATED_TIME_ASCENDING"
	SortKeyType_LAST_AUTHENTICATED_TIME_DESCENDING SortKeyType = "LAST_AUTHENTICATED_TIME_DESCENDING"
	SortKeyType_SERVICE_NAMESPACE_ASCENDING        SortKeyType = "SERVICE_NAMESPACE_ASCENDING"
	SortKeyType_SERVICE_NAMESPACE_DESCENDING       SortKeyType = "SERVICE_NAMESPACE_DESCENDING"
)

type StatusType string

const (
	StatusType_Active   StatusType = "Active"
	StatusType_Inactive StatusType = "Inactive"
)

type SummaryKeyType string

const (
	SummaryKeyType_AccessKeysPerUserQuota            SummaryKeyType = "AccessKeysPerUserQuota"
	SummaryKeyType_AccountAccessKeysPresent          SummaryKeyType = "AccountAccessKeysPresent"
	SummaryKeyType_AccountMFAEnabled                 SummaryKeyType = "AccountMFAEnabled"
	SummaryKeyType_AccountPasswordPresent            SummaryKeyType = "AccountPasswordPresent"
	SummaryKeyType_AccountSigningCertificatesPresent SummaryKeyType = "AccountSigningCertificatesPresent"
	SummaryKeyType_AttachedPoliciesPerGroupQuota     SummaryKeyType = "AttachedPoliciesPerGroupQuota"
	SummaryKeyType_AttachedPoliciesPerRoleQuota      SummaryKeyType = "AttachedPoliciesPerRoleQuota"
	SummaryKeyType_AttachedPoliciesPerUserQuota      SummaryKeyType = "AttachedPoliciesPerUserQuota"
	SummaryKeyType_GlobalEndpointTokenVersion        SummaryKeyType = "GlobalEndpointTokenVersion"
	SummaryKeyType_GroupPolicySizeQuota              SummaryKeyType = "GroupPolicySizeQuota"
	SummaryKeyType_Groups                            SummaryKeyType = "Groups"
	SummaryKeyType_GroupsPerUserQuota                SummaryKeyType = "GroupsPerUserQuota"
	SummaryKeyType_GroupsQuota                       SummaryKeyType = "GroupsQuota"
	SummaryKeyType_MFADevices                        SummaryKeyType = "MFADevices"
	SummaryKeyType_MFADevicesInUse                   SummaryKeyType = "MFADevicesInUse"
	SummaryKeyType_Policies                          SummaryKeyType = "Policies"
	SummaryKeyType_PoliciesQuota                     SummaryKeyType = "PoliciesQuota"
	SummaryKeyType_PolicySizeQuota                   SummaryKeyType = "PolicySizeQuota"
	SummaryKeyType_PolicyVersionsInUse               SummaryKeyType = "PolicyVersionsInUse"
	SummaryKeyType_PolicyVersionsInUseQuota          SummaryKeyType = "PolicyVersionsInUseQuota"
	SummaryKeyType_ServerCertificates                SummaryKeyType = "ServerCertificates"
	SummaryKeyType_ServerCertificatesQuota           SummaryKeyType = "ServerCertificatesQuota"
	SummaryKeyType_SigningCertificatesPerUserQuota   SummaryKeyType = "SigningCertificatesPerUserQuota"
	SummaryKeyType_UserPolicySizeQuota               SummaryKeyType = "UserPolicySizeQuota"
	SummaryKeyType_Users                             SummaryKeyType = "Users"
	SummaryKeyType_UsersQuota                        SummaryKeyType = "UsersQuota"
	SummaryKeyType_VersionsPerPolicyQuota            SummaryKeyType = "VersionsPerPolicyQuota"
)
