// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
)

// RoleTagsSpec defines the desired state of RoleTags.
type RoleTagsSpec struct {
	Key *string `json:"key,omitempty"`
	// The name of the IAM role to which you want to add tags.
	//
	// This parameter accepts (through its regex pattern (http://wikipedia.org/wiki/regex))
	// a string of characters that consist of upper and lowercase alphanumeric characters
	// with no spaces. You can also include any of the following characters: _+=,.@-
	//
	// Regex Pattern: `^[\w+=,.@-]+$`
	// +kubebuilder:validation:Required
	RoleName *string   `json:"roleName"`
	TagKeys  []*string `json:"tagKeys,omitempty"`
	// The list of tags that you want to attach to the IAM role. Each tag consists
	// of a key name and an associated value.
	// +kubebuilder:validation:Required
	Tags []*Tag `json:"tags"`
}

// RoleTagsStatus defines the observed state of RoleTags
type RoleTagsStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
}

// RoleTags is the Schema for the RoleTags API
type RoleTags struct {
	Spec   RoleTagsSpec   `json:"spec,omitempty"`
	Status RoleTagsStatus `json:"status,omitempty"`
}
