// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
)

// RolePermissionsBoundarySpec defines the desired state of RolePermissionsBoundary.
type RolePermissionsBoundarySpec struct {

	// The ARN of the managed policy that is used to set the permissions boundary
	// for the role.
	//
	// A permissions boundary policy defines the maximum permissions that identity-based
	// policies can grant to an entity, but does not grant permissions. Permissions
	// boundaries do not define the maximum permissions that a resource-based policy
	// can grant to an entity. To learn more, see Permissions boundaries for IAM
	// entities (https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html)
	// in the IAM User Guide.
	//
	// For more information about policy types, see Policy types (https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html#access_policy-types)
	// in the IAM User Guide.
	// +kubebuilder:validation:Required
	PermissionsBoundary *string `json:"permissionsBoundary"`
	// The name (friendly name, not ARN) of the IAM role for which you want to set
	// the permissions boundary.
	//
	// Regex Pattern: `^[\w+=,.@-]+$`
	// +kubebuilder:validation:Required
	RoleName *string `json:"roleName"`
}

// RolePermissionsBoundaryStatus defines the observed state of RolePermissionsBoundary
type RolePermissionsBoundaryStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
}

// RolePermissionsBoundary is the Schema for the RolePermissionsBoundaries API
type RolePermissionsBoundary struct {
	Spec   RolePermissionsBoundarySpec   `json:"spec,omitempty"`
	Status RolePermissionsBoundaryStatus `json:"status,omitempty"`
}
